global:
 message: Welcome to customer service dev Environment
server:
 port: 8080
message: Hello from dev!
spring: 
 datasource:
  url: jdbc:mysql://localhost:3306/cust_master
  username: vivek
  password: root
 jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  

   
