global:
 message: Welcome to customer service dev Environment
server:
 port: 8080
message: Hello from dev!
spring: 
 datasource:
  url: jdbc:mysql://localhost:3306/cust_master
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: root
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  

   
