spring:
 application:
  name: customer-microservice
 datasource:
  url: jdbc:mysql://localhost:3306/customer_master
  driverClassName: com.mysql.cj.jdbc.Driver
 java:
  hibernate: 
   ddl-auto: none
  show-sql: false
  
