
global:
 message: Welcome to order service dev Environment
server:
 port: 8084
message: Hello from dev!
spring: 
 datasource:
  url: jdbc:h2:mem:order_master
  username: root
  password: root
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
